<?php
/**
 * Created by PhpStorm.
 * User: max
 * Date: 24.02.2018
 * Time: 13:25
 */

namespace Core\Composite;


abstract class CompositeArmy extends Unit
{
    private $units = array();

    function getComposite()
    {
        return $this;
    }

    function addUnit(Unit $unit)
    {
        if (in_array($unit, $this->units, true)) {
            return;
        }
        if((count($this->units)+count($unit)) > 10) {
            throw new \Exception('Maximum 10 units');
        }
        $this->units[] = $unit;
    }

    function removeUnit(Unit $unit)
    {
        parent::removeUnit($unit); // TODO: Change the autogenerated stub
    }

    function getUnits()
    {
        return $this->units;
    }

    function bombardStrength()
    {
        return 0;
    }
}